name: brainy
channels:
  - anaconda
  - pytorch
  - conda-forge
  - pypi
dependencies:
  - python=3.9.20
  - pytorch=2.4.1
  - snntorch=0.9.1
  - seaborn=0.13.2
  - matplotlib=3.9.2
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - numpy=2.0.1